elasticsearchVersion = 8.17.0
opensearchVersion = 2.19.0
luceneVersion = 9.12.0
jacksonDataBindVersion = 2.17.2
log10xDecoderVersion = 0.9.0
l1esVersion = 0.9.0

pluginName = l1es-plugin
pluginDesc = Log10x support for searching and decoding encoded data in Elasticsearch
pluginClassname = org.elasticsearch.plugin.log10x.L1esPlugin
