description=Log10x support for searching and decoding encoded data in Elasticsearch
version=0.9.0.es.8.17.0
name=l1es-plugin
classname=org.elasticsearch.plugin.log10x.L1esPlugin
java.version=17
elasticsearch.version=8.17.0
