description=Log10x support for searching and decoding encoded data in OpenSearch
version=0.9.0.os.2.19.0
name=l1es-plugin
classname=org.opensearch.plugin.log10x.L1esPlugin
java.version=17
opensearch.version=2.19.0
